Repository boostcampwm-2024/web08-BooQuiz, pull requests merged in 2024-11, with the labels that each got.

#32 chore: prettier
  .gitignore
  .prettierrc
Labels: ⚙ Setting

#34 Feature/#33 frontend environment setting
  apps/frontend/components.json
  apps/frontend/package.json
  apps/frontend/postcss.config.js
  apps/frontend/src/components/ui/button.tsx
  apps/frontend/src/index.css
  apps/frontend/src/lib/utils.ts
  apps/frontend/tailwind.config.js
  apps/frontend/tsconfig.app.json
  apps/frontend/tsconfig.json
  apps/frontend/tsconfig.node.json
  apps/frontend/vite.config.ts
  package-lock.json
  package.json
Labels: ⚙ Setting

#36 feat: 서버 퀴즈존 생성 구현
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  apps/backend/.gitignore
  apps/backend/README.md
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/main.ts
  apps/backend/src/quiz-zone/dto/create-quiz-zone.dto.ts
  apps/backend/src/quiz-zone/dto/update-quiz-zone.dto.ts
  apps/backend/src/quiz-zone/entities/player.entity.ts
  apps/backend/src/quiz-zone/entities/quiz-zone.entity.ts
  apps/backend/src/quiz-zone/entities/quiz.entity.ts
  apps/backend/src/quiz-zone/entities/submitted.quiz.ts
  apps/backend/src/quiz-zone/quiz-zone.controller.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.controller.ts
  apps/backend/src/quiz-zone/quiz-zone.module.ts
  apps/backend/src/quiz-zone/quiz-zone.repository.interface.ts
  apps/backend/src/quiz-zone/quiz-zone.repository.memory.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.repository.memory.ts
  apps/backend/src/quiz-zone/quiz-zone.service.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.service.ts
  apps/backend/test/app.e2e-spec.ts
  apps/backend/test/quiz-zone.e2e-spec.ts
  apps/backend/tsconfig.json
  package-lock.json
Labels: ✨ Feature, ✅ Test

#45 Feature/#2 메인페이지, 퀴즈 대기실 페이지
  apps/frontend/src/pages/MainPage.tsx
  apps/frontend/src/pages/QuizZoneWaitingPage.tsx
Labels: ✨ Feature

#54 Feature/#51 CustomAlert
  apps/frontend/package.json
  apps/frontend/src/components/common/CustomAlert.stories.tsx
  apps/frontend/src/components/common/CustomAlert.tsx
  apps/frontend/src/components/ui/alert-dialog.tsx
  pnpm-lock.yaml
Labels: ✨ Feature

#55 Feature/#52 텍스트 복사 컴포넌트
  apps/frontend/src/components/common/TextCopy.stories.tsx
  apps/frontend/src/components/common/TextCopy.tsx
  apps/frontend/src/components/common/Typogrpahy.tsx
Labels: ✨ Feature

#44 feat: 서버 측 퀴즈 풀이 진행
  .idea/codeStyles/Project.xml
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/main.ts
  apps/backend/src/play/dto/current-quiz.dto.ts
  apps/backend/src/play/dto/quiz-result-summary.dto.ts
  apps/backend/src/play/dto/quiz-submit.dto.ts
  apps/backend/src/play/entities/play.entity.ts
  apps/backend/src/play/play.gateway.spec.ts
  apps/backend/src/play/play.gateway.ts
  apps/backend/src/play/play.module.ts
  apps/backend/src/play/play.service.spec.ts
  apps/backend/src/play/play.service.ts
  apps/backend/src/quiz-zone/dto/update-quiz-zone.dto.ts
  apps/backend/src/quiz-zone/dto/waiting-quiz-zone.dto.ts
  apps/backend/src/quiz-zone/entities/player.entity.ts
  apps/backend/src/quiz-zone/entities/quiz-zone.entity.ts
  apps/backend/src/quiz-zone/entities/quiz.entity.ts
  apps/backend/src/quiz-zone/entities/submitted-quiz.entity.ts
  apps/backend/src/quiz-zone/entities/submitted.quiz.ts
  apps/backend/src/quiz-zone/quiz-zone.controller.ts
  apps/backend/src/quiz-zone/quiz-zone.module.ts
  apps/backend/src/quiz-zone/quiz-zone.repository.interface.ts
  apps/backend/src/quiz-zone/quiz-zone.repository.memory.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.repository.memory.ts
  apps/backend/src/quiz-zone/quiz-zone.service.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.service.ts
  apps/backend/src/quiz-zone/repository/quiz-zone.memory.repository.spec.ts
  apps/backend/src/quiz-zone/repository/quiz-zone.memory.repository.ts
  apps/backend/src/quiz-zone/repository/quiz-zone.repository.interface.ts
  apps/backend/test/app.e2e-spec.ts
  apps/backend/test/play.e2e-spec.ts
  package.json
  pnpm-lock.yaml
Labels: 📬 API, ✨ Feature

#58 Feature/#56 퀴즈존 퍼널 컴포넌트 구현
  apps/frontend/src/hook/useQuizZoneManager.tsx
  apps/frontend/src/hook/useTimer.ts
Labels: ✨ Feature

#62 feature/#5-websocket-test-code
  apps/backend/src/play/play.gateway.spec.ts
  apps/backend/src/play/play.service.spec.ts
  apps/backend/src/play/play.service.ts
Labels: ✅ Test

#61 chore: 프론트엔드 배포용 yml 파일 작성
  .github/workflows/deploy-be.yml
  .github/workflows/deploy-fe.yml
  .github/workflows/test.yml
  apps/frontend/src/blocks/QuizZone/QuizInProgress.tsx
  apps/frontend/src/components/common/CustomAlert.stories.tsx
  apps/frontend/src/hook/useQuizZoneManager.tsx
Labels: ⚙ Setting

#67 chore: 환경 변수 설정
  apps/backend/config/http.config.ts
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/main.ts
  pnpm-lock.yaml
Labels: ⚙ Setting

#95 chore: winston 반영 및 예시 추가
  apps/backend/package.json
  apps/backend/src/app.controller.spec.ts
  apps/backend/src/app.module.ts
  apps/backend/src/app.service.ts
  apps/backend/src/logger/http-logger.middleware.ts
  apps/backend/src/logger/winston.config.ts
  pnpm-lock.yaml
Labels: ⚙ Setting

#96 chore: github action 설정 변경
  .github/workflows/deploy-be.yml
  .github/workflows/deploy-fe.yml
  apps/backend/src/main.ts
Labels: ⚙ Setting

#102 Feature/#101 use timer test
  apps/frontend/package.json
  apps/frontend/src/hook/useTimer.test.ts
  apps/frontend/src/test/setup.ts
  apps/frontend/tsconfig.json
  apps/frontend/vite.config.ts
  pnpm-lock.yaml
Labels: ⚙ Setting, ✅ Test

#114 refactor: 퀴즈존 리포지토리 리펙토링
  apps/backend/src/play/play.gateway.ts
  apps/backend/src/play/play.service.ts
  apps/backend/src/quiz-zone/quiz-zone.service.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.service.ts
  apps/backend/src/quiz-zone/repository/quiz-zone.memory.repository.spec.ts
  apps/backend/src/quiz-zone/repository/quiz-zone.memory.repository.ts
  apps/backend/src/quiz-zone/repository/quiz-zone.repository.interface.ts
Labels: 🔨 Refactor

#112 Feature/#98 quiz zone manager refactor
  apps/frontend/src/blocks/QuizZone/QuizInProgress.tsx
  apps/frontend/src/blocks/QuizZone/QuizWaiting.tsx
  apps/frontend/src/blocks/QuizZone/QuizZoneInProgress.tsx
  apps/frontend/src/blocks/QuizZone/QuizZoneLobby.tsx
  apps/frontend/src/blocks/QuizZone/QuizZoneResult.tsx
  apps/frontend/src/components/common/CustomAlertDialog.tsx
  apps/frontend/src/components/common/ParticipantGrid.tsx
  apps/frontend/src/hook/quizZone/useQuizZone.test.ts
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/hook/useQuizZoneManager.tsx
  apps/frontend/src/hook/useTimer.test.ts
  apps/frontend/src/hook/useTimer.ts
  apps/frontend/src/hook/useWebSocket.tsx
  apps/frontend/src/pages/MainPage.tsx
  apps/frontend/src/pages/QuiZonePage.tsx
  apps/frontend/src/pages/QuizZonePage.tsx
  apps/frontend/src/router/router.tsx
  apps/frontend/src/types/quizZone.types.ts
  commitlint.config.cjs
Labels: 🔨 Refactor

#119 [Chore] 백엔드 WebSocketAdapter 커스터마이징
  apps/backend/src/core/SessionWsAdapter.ts
  apps/backend/src/main.ts
Labels: ⚙ Setting, 🔨 Refactor

#158 chore: test, deploy 분리
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-frontend.yml
  .github/workflows/test-backend.yml
  .github/workflows/test-frontend.yml
Labels: ⚙ Setting

#155 Feature/#154 errorboundary
  apps/frontend/src/components/boundary/AsyncBoundary.tsx
  apps/frontend/src/components/boundary/ErrorBoundary.tsx
  apps/frontend/src/hook/useAsyncError.ts
  apps/frontend/src/types/error.types.ts
  apps/frontend/src/utils/errorUtils.ts
Labels: ✨ Feature

#162 feature/#124-fe-quiz-summary
  apps/backend/config/typeorm.config.ts
  apps/backend/src/app.module.ts
  apps/backend/src/main.ts
  apps/backend/src/play/dto/submit-response.dto.ts
  apps/backend/src/play/play.gateway.ts
  apps/backend/src/play/play.service.spec.ts
  apps/backend/src/play/play.service.ts
  apps/frontend/src/blocks/QuizZone/QuizCompleted.tsx
  apps/frontend/src/blocks/QuizZone/QuizInProgress.tsx
  apps/frontend/src/blocks/QuizZone/QuizWaiting.tsx
  apps/frontend/src/blocks/QuizZone/QuizZoneInProgress.tsx
  apps/frontend/src/components/common/ParticipantGrid.tsx
  apps/frontend/src/components/common/PlayersGrid.tsx
  apps/frontend/src/components/common/TooltipWrapper.tsx
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/hook/useWebSocket.tsx
  apps/frontend/src/types/quizZone.types.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#163 [Feat] 채팅 기능 추가를 위한 ui 및 백엔드 작업
  apps/backend/src/play/play.gateway.ts
  apps/backend/src/play/play.service.spec.ts
  apps/backend/src/play/play.service.ts
  apps/backend/src/quiz-zone/dto/check-existing-quiz-zone.dto.ts
  apps/backend/src/quiz-zone/quiz-zone.controller.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.controller.ts
  apps/backend/src/quiz-zone/quiz-zone.service.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.service.ts
  apps/backend/src/quiz/entity/quiz-set.entity.ts
  apps/backend/src/quiz/entity/quiz.entitiy.ts
  apps/frontend/src/blocks/QuizZone/QuizCompleted.tsx
  apps/frontend/src/blocks/QuizZone/QuizInProgress.tsx
  apps/frontend/src/blocks/QuizZone/QuizWaiting.tsx
  apps/frontend/src/blocks/QuizZone/QuizZoneLobby.tsx
  apps/frontend/src/blocks/QuizZone/QuizZoneResult.tsx
  apps/frontend/src/components/common/ChatBox.tsx
  apps/frontend/src/components/common/ContentBox.tsx
  apps/frontend/src/components/common/Input.tsx
  apps/frontend/src/components/common/NavBar.tsx
  apps/frontend/src/components/common/PlayersGrid.tsx
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/pages/MainPage.tsx
  apps/frontend/src/pages/QuizZonePage.tsx
  apps/frontend/src/pages/RootLayout.tsx
  apps/frontend/src/types/quizZone.types.ts
Labels: ✨ Feature

#192 [FE] 퀴즈존 생성 처리 및 퀴즈셋 생성 처리 구현
  apps/backend/.gitignore
  apps/backend/src/common/constants.ts
  apps/backend/src/play/play.service.spec.ts
  apps/backend/src/quiz-zone/dto/create-quiz-zone.dto.ts
  apps/backend/src/quiz/dto/create-quiz-request.dto.ts
  apps/backend/src/quiz/dto/search-quiz-set-request.dto.ts
  apps/backend/src/quiz/quiz.controller.spec.ts
  apps/backend/src/quiz/quiz.controller.ts
  apps/backend/src/quiz/quiz.service.spec.ts
  apps/backend/src/quiz/quiz.service.ts
  apps/backend/test/quiz.e2e-spec.ts
  apps/frontend/src/blocks/CreateQuizZone/CandidateQuizzes.tsx
  apps/frontend/src/blocks/CreateQuizZone/CreateQuiz.tsx
  apps/frontend/src/blocks/CreateQuizZone/CreateQuizSet.tsx
  apps/frontend/src/blocks/CreateQuizZone/CreateQuizZoneBasic.tsx
  apps/frontend/src/blocks/CreateQuizZone/SearchQuizSet.tsx
  apps/frontend/src/blocks/CreateQuizZone/SearchQuizSetResults.tsx
  apps/frontend/src/constants/quiz-set.constants.ts
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/hook/useValidInput.ts
  apps/frontend/src/pages/CreateQuizZonePage.tsx
  apps/frontend/src/pages/MainPage.tsx
  apps/frontend/src/router/router.tsx
  apps/frontend/src/types/create-quiz-zone.types.ts
  apps/frontend/src/types/quizZone.types.ts
  apps/frontend/src/utils/requests.ts
  apps/frontend/src/utils/validators.ts
Labels: ✨ Feature

#195 Feature/#169 quiz zone form
  apps/frontend/src/blocks/CreateQuizZone/CandidateQuizzes.tsx
  apps/frontend/src/blocks/CreateQuizZone/CreateQuiz.tsx
  apps/frontend/src/blocks/CreateQuizZone/CreateQuizSet.tsx
  apps/frontend/src/blocks/CreateQuizZone/CreateQuizZoneBasic.tsx
  apps/frontend/src/blocks/CreateQuizZone/SearchQuizSet.tsx
  apps/frontend/src/blocks/CreateQuizZone/SearchQuizSetResults.tsx
  apps/frontend/src/components/common/Input.tsx
  apps/frontend/src/pages/CreateQuizZonePage.tsx
  apps/frontend/src/utils/validators.ts
Labels: ✨ Feature, 🎨 Html&css

#199 4차 배포
  README.md
  apps/backend/.gitignore
  apps/backend/README.md
  apps/backend/config/database.config.ts
  apps/backend/src/common/base-entity.ts
  apps/backend/src/common/constants.ts
  apps/backend/src/play/play.service.spec.ts
  apps/backend/src/quiz-zone/dto/create-quiz-zone.dto.ts
  apps/backend/src/quiz-zone/entities/quiz.entity.ts
  apps/backend/src/quiz-zone/quiz-zone.controller.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.controller.ts
  apps/backend/src/quiz-zone/quiz-zone.module.ts
  apps/backend/src/quiz-zone/quiz-zone.service.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.service.ts
  apps/backend/src/quiz/dto/create-quiz-request.dto.ts
  apps/backend/src/quiz/dto/search-quiz-set-request.dto.ts
  apps/backend/src/quiz/dto/search-quiz-set-response.dto.ts
  apps/backend/src/quiz/entity/quiz-set.entity.ts
  apps/backend/src/quiz/entity/quiz.entitiy.ts
  apps/backend/src/quiz/quiz-set.controller.spec.ts
  apps/backend/src/quiz/quiz-set.controller.ts
  apps/backend/src/quiz/quiz.controller.spec.ts
  apps/backend/src/quiz/quiz.controller.ts
  apps/backend/src/quiz/quiz.module.ts
  apps/backend/src/quiz/quiz.service.spec.ts
  apps/backend/src/quiz/quiz.service.ts
  apps/backend/test/quiz.e2e-spec.ts
  apps/frontend/README.md
  apps/frontend/src/blocks/CreateQuizZone/CandidateQuizzes.tsx
  apps/frontend/src/blocks/CreateQuizZone/CreateQuiz.tsx
  apps/frontend/src/blocks/CreateQuizZone/CreateQuizSet.tsx
  apps/frontend/src/blocks/CreateQuizZone/CreateQuizZoneBasic.tsx
  apps/frontend/src/blocks/CreateQuizZone/SearchQuizSet.tsx
  apps/frontend/src/blocks/CreateQuizZone/SearchQuizSetResults.tsx
  apps/frontend/src/components/common/Input.tsx
  apps/frontend/src/constants/quiz-set.constants.ts
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/hook/useValidInput.ts
  apps/frontend/src/pages/CreateQuizZonePage.tsx
  apps/frontend/src/pages/MainPage.tsx
  apps/frontend/src/router/router.tsx
  apps/frontend/src/types/create-quiz-zone.types.ts
  apps/frontend/src/types/quizZone.types.ts
  apps/frontend/src/utils/requests.ts
  apps/frontend/src/utils/validators.ts
Labels: ✨ Feature

#203 최종 결과 정리 UI 오류 수정
  apps/frontend/src/blocks/QuizZone/QuizZoneResult.tsx
  apps/frontend/src/types/quizZone.types.ts
Labels: 🐞 BugFix

#204 fix: FE 이벤트 데이터 수신 처리 수정
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/types/quizZone.types.ts
Labels: 🐞 BugFix
