Repository boostcampwm-2024/web08-BooQuiz, pull requests merged in 2024-12, with the labels that each got.

#216 퀴즈존 입장시 기존 퀴즈존이 아닐 경우 얼럿 노출
  apps/backend/src/quiz-zone/dto/create-quiz-zone.dto.ts
  apps/backend/src/quiz-zone/quiz-zone.controller.ts
  apps/backend/src/quiz/dto/create-quiz-request.dto.ts
  apps/frontend/src/components/common/CustomAlert.tsx
  apps/frontend/src/components/common/CustomAlertDialogContent.tsx
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/pages/MainPage.tsx
Labels: ✨ Feature, 🔨 Refactor, 🐞 BugFix

#213 refactor: 닉네임 생성 로직 변경 및 접두사/접미사 나누기
  apps/backend/src/common/constants.ts
Labels: 🔨 Refactor

#217 [Feature] 로비에서 퀴즈존 최대인원 확인
  apps/backend/src/quiz-zone/dto/find-quiz-zone.dto.ts
  apps/backend/src/quiz-zone/quiz-zone.service.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.service.ts
  apps/backend/src/quiz/quiz.service.spec.ts
  apps/backend/src/quiz/quiz.service.ts
  apps/frontend/src/blocks/QuizZone/QuizZoneLobby.tsx
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/pages/QuizZonePage.tsx
  apps/frontend/src/types/quizZone.types.ts
Labels: ✨ Feature

#225 feature/fe-websocket-reconnect
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/hook/useWebSocket.tsx
  apps/frontend/src/pages/QuizZonePage.tsx
  apps/frontend/src/utils/requests.ts
Labels: ✨ Feature

#224 [Feature] submit 혹은 입장시에 서버에서 관리하는 채팅 받기
  apps/backend/src/app.module.ts
  apps/backend/src/chat/chat.controller.spec.ts
  apps/backend/src/chat/chat.controller.ts
  apps/backend/src/chat/chat.module.ts
  apps/backend/src/chat/chat.service.spec.ts
  apps/backend/src/chat/chat.service.ts
  apps/backend/src/chat/entities/chat-message.entity.ts
  apps/backend/src/chat/repository/chat.memory.repository.spec.ts
  apps/backend/src/chat/repository/chat.memory.repository.ts
  apps/backend/src/play/dto/submit-response.dto.ts
  apps/backend/src/play/play.gateway.spec.ts
  apps/backend/src/play/play.gateway.ts
  apps/backend/src/play/play.module.ts
  apps/backend/src/play/play.service.spec.ts
  apps/backend/src/quiz-zone/dto/find-quiz-zone.dto.ts
  apps/backend/src/quiz-zone/quiz-zone.controller.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.controller.ts
  apps/backend/src/quiz-zone/quiz-zone.module.ts
  apps/backend/src/quiz-zone/quiz-zone.service.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.service.ts
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/types/quizZone.types.ts
Labels: 📬 API, ✨ Feature

#227 Feature/conflict UI fix
  apps/frontend/src/blocks/CreateQuizZone/CreateQuiz.tsx
  apps/frontend/src/blocks/CreateQuizZone/CreateQuizSet.tsx
  apps/frontend/src/blocks/CreateQuizZone/CreateQuizZoneBasic.tsx
  apps/frontend/src/blocks/QuizZone/QuizZoneResult.tsx
  apps/frontend/src/components/common/Input.tsx
  apps/frontend/src/pages/MainPage.tsx
  apps/frontend/src/pages/QuizZonePage.tsx
  apps/frontend/src/utils/validators.ts
Labels: 🐞 BugFix

#226 feature/fe-websocket-reconnect
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/pages/QuizZonePage.tsx
  apps/frontend/src/utils/requests.ts
Labels: 🐞 BugFix

#234 방장 나가기 발생했을 때 소켓 연결 끊음 처리 및 얼럿 노출
  apps/backend/src/play/entities/quiz-summary.entity.ts
  apps/backend/src/play/entities/rank.entity.ts
  apps/backend/src/play/play.gateway.ts
  apps/backend/src/play/play.service.ts
  apps/backend/src/quiz-zone/dto/find-quiz-zone.dto.ts
  apps/backend/src/quiz-zone/entities/quiz-zone.entity.ts
  apps/backend/src/quiz-zone/quiz-zone.service.spec.ts
  apps/backend/src/quiz-zone/quiz-zone.service.ts
  apps/frontend/src/blocks/CreateQuizZone/CreateQuizZoneBasic.tsx
  apps/frontend/src/components/common/Input.tsx
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/utils/validators.ts
Labels: 🔨 Refactor, 🐞 BugFix

#244 feature/host-close
  apps/frontend/src/hook/quizZone/useQuizZone.tsx
  apps/frontend/src/hook/useTimer.ts
  apps/frontend/src/pages/QuizZonePage.tsx
Labels: 🔨 Refactor, 🐞 BugFix

#246 fix: 방장 종료창 노출 조건 추가
  apps/frontend/src/blocks/QuizZone/QuizZoneLobby.tsx
  apps/frontend/src/pages/QuizZonePage.tsx
Labels: 🐞 BugFix
